### PR TITLE
added labMT sentiment dictionary

### PR DESCRIPTION
**Pull request by andyreagan**
also fixed a bug with loading the loughran data

### CODE REVIEW

**Comment by andyreagan** [comment]
Looks like the appveyor broke because the docs don't line up with new function call for `get_sentiments`.

**Comment by Ironholds** [comment]
Heya; want me to take a stab at integrating this and shutting appveyor up?

**Comment by andyreagan** [comment]
That would be awesome! My limited knowledge of R is holding up any progress on my end.

**Comment by Ironholds** [comment]
Okay, working on this this evening; lacking write access I'm gonna fork and incorporate distinctly, and slot you into all the contributor slots, if that works?

**Comment by juliasilge** [comment]
We are getting ready for our immediate CRAN submission (0.1.3) and we plan to implement some internationalization changes (including this PR!) *after* that submission in preparation for tidytext 0.1.4.

**Comment by juliasilge** [comment]
@andyreagan First off, I would like to apologize for being so tardy in addressing this PR. Thank you so much for your interest in this project!

The actual code in this PR is now pretty far behind the current development version but I am interested in implementing the labMT lexicon, if we can! To start with, can you tell me the source for these datasets? The link in this PR is broken. I am a bit concerned about how we got to other languages since it looks like the [original labMT paper](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0026752) only has [English words](http://journals.plos.org/plosone/article/file?id=info%3Adoi/10.1371/journal.pone.0026752.s001&type=supplementary). If nothing else, it would be great to have another English lexicon.

**Comment by andyreagan** [comment]
@juliasilge thanks!

There was a follow up paper that expanded the survey for the 10,000 most used words in 10 languages, all rated by native speakers. The paper is here: http://www.pnas.org/content/112/8/2389.full (and the arXiv version for paywall free: https://arxiv.org/abs/1406.3855).

The full data is available here:
http://www.uvm.edu/storylab/share/papers/dodds2015a/data.html

**Comment by andyreagan** [comment]
It's probably unnecessary to add _all_ the sentiment dictionaries here, but I tried to pull together a comprehensive list of the freely available one here: https://github.com/massmutual/sentidict/tree/master/sentidict/data

That's likely to be missing a few, since it's 9 months old, but there are 24 of them there.
The script `dictionaries.py` has some details about each of the dictionaries, here it the class for ANEW (has citation, license, score type info):
https://github.com/massmutual/sentidict/blob/master/sentidict/dictionaries.py#L356

**Comment by juliasilge** [comment]
Well, this PR is now quite old (my fault) and we are thinking through how we've handled licensing for the existing sentiment lexicons in #131 so I am going to close this PR. I *would* love to eventually add more sentiment lexicons but we'll need to start afresh, with a different approach.

Thank you so much for your interest and investment in tidytext @andyreagan! 🙌

**Comment by andyreagan** [comment]
I was just revisiting this myself with the thought to close and start again
from the master branch. I'll take a look at the PR you mentioned.

**Comment by andyreagan** [comment]
And thanks for the very kind words :)

**Pull request closed without merging**
