### PR TITLE
Added support for 17 foreign languages & for custom dictionaries

### PR DESCRIPTION
**Pull request by ColinFay**
Added support for 17 foreign languages + it's now possible to pass a custom hunspell dictionary.

List of default supported languages is returned with

```r
supported_languages()
 [1] "english"             "bulgarian"           "croatian"            "danish"              "dutch"              
 [6] "french"              "german"              "greek"               "icelandic"           "italian"            
[11] "norwegian"           "polish"              "portuguese_european" "russian"             "slovenian"          
[16] "spanish"             "swedish"             "turkish"             "custom"  
```
tokenization is handled by modified functions from the {tokenizers} package (see utils.R and tokenizers_foreign.R) 

Foreign languages can be parsed as usual (ngrams, html, etc).

Added a Vignette about foreign languages.

Examples : 

```r
library(tidytext)
library(dplyr)
supported_languages()
fr <- tibble::tibble(txt = c("C'est dans l'arrière-cuisine. On s'en sert pour ranger.", 
                            "On aime l'arrière-saison. On part toujours en vacances à ce moment"))

fr %>% unnest_tokens(word, txt, lang = "french")
# A tibble: 25 x 1
      word
     <chr>
 1       c
 2     est
 3    dans
 4       l
 5 arrière
 6 cuisine
 7      on
 8       s
 9      en
10    sert
# ... with 15 more rows

fr %>% unnest_tokens(ngram, txt, token = "ngrams", n = 2, lang = "french")
# A tibble: 24 x 1
             ngram
             <chr>
 1           c est
 2        est dans
 3          dans l
 4       l arrière
 5 arrière cuisine
 6      cuisine on
 7            on s
 8            s en
 9         en sert
10       sert pour
# ... with 14 more rows

data_frame(row = 1:2,
                 text = c("<h1>Du text <b>ici</b>", "<a href='example.com'>C'est l'ancien site</a>")) %>%
   unnest_tokens(word, text, format = "html", lang = "french")
# A tibble: 8 x 2
    row   word
  <int>  <chr>
1     1     du
2     1   text
3     1    ici
4     2      c
5     2    est
6     2      l
7     2 ancien
8     2   site

tibble::tibble(txt = c("Mir geht’s nicht gut.", 
                             "Darf ich mit Kreditkarte bezahlen? ")) %>% 
  unnest_tokens(word, txt, lang = "german")
# A tibble: 10 x 1
          word
         <chr>
 1         mir
 2        geht
 3           s
 4       nicht
 5         gut
 6        darf
 7         ich
 8         mit
 9 kreditkarte
10    bezahlen


# turkish
tibble::tibble(txt = c("İyiyim teşekkür ederim, siz nasılsınız", 
                             "Türkçe konuşur musunuz?")) %>% 
  unnest_tokens(word, txt, lang = "turkish")
# A tibble: 8 x 1
        word
       <chr>
1     i̇yiyim
2   teşekkür
3     ederim
4        siz
5 nasılsınız
6     türkçe
7    konuşur
8    musunuz

#russian 

tibble::tibble(txt = c("Говорите, пожалуйста, медленнее. Вы говорите по-английски?", 
                       "К сожалению, мне (нам) пора идти.")) %>% 
  unnest_tokens(word, txt, lang = "russian")
# A tibble: 13 x 1
         word
        <chr>
 1   говорите
 2 пожалуйста
 3  медленнее
 4         вы
 5   говорите
 6         по
 7  английски
 8          к
 9  сожалению
10        мне
11        нам
12       пора
13       идти
```

With a custom dictionary 

```r
df_latin <- tibble(text = "Alea Jacta Est.")
download.file("https://raw.githubusercontent.com/titoBouzout/Dictionaries/master/la.aff", "la.aff")
unnest_tokens(df_latin, word, text, lang = "custom", dict = "la.aff") 
# A tibble: 3 x 1
   word
  <chr>
1  alea
2 jacta
3   est
```

### CODE REVIEW

**Comment by juliasilge** [comment]
This will be a great addition to this package, @ColinFay! I am looking at these various errors. For starters, have you checked how this support for other languages [performs on Windows](https://ci.appveyor.com/project/juliasilge/tidytext/build/1.0.149)? Looks like it's failing right now.

**Comment by ColinFay** [comment]
This might be a file issue with the vignette (the french dict was named "French.aff", not "french.aff"), so `match_arg` with `supported_languages()` in `unnest_tokens()` failed. 

Just changed the name, and I'll have a closer look to the error tomorrow :)

**Comment by ColinFay** [comment]
Hi @juliasilge 

This seems to be fixed!

Not sure why but I have error when running the tests on my travis account : https://travis-ci.org/ColinFay/tidytext/builds/307761654  

But these errors are not picked up by the travis on the PR build https://travis-ci.org/juliasilge/tidytext/builds/307761688 

No error neither when `devtools::check()` on my computer. 

Tell me if everything is ok on your side. 

Colin

**Comment by juliasilge** [comment]
This is passing now! I had to fix some merge conflicts so this might involve some more fussing on my part. Thanks so much for your work on this! 🙌🙌🙌

**Comment by juliasilge** [comment]
@ColinFay Where did these dictionaries come from? Do we have the rights to include them under our license?

**Comment by ColinFay** [comment]
hi, 
Thanks for merging this PR :) 

The dictionaries come from https://github.com/titoBouzout/Dictionaries, which are dictionaries dowloaded and converted from https://extensions.openoffice.org/en 

The open office licence is LGPL : https://www.openoffice.org/license.html, which seems to be MIT compatible, as GPL is. 

The source link is in https://github.com/juliasilge/tidytext/blob/master/R/utils.R, but maybe I should also link to the openoffice page?

**Comment by juliasilge** [comment]
Well @ColinFay I have some bad news, I'm afraid, after working with this PR for a bit over the last few days. 😕 I should have looked in more detail before accepting, I'm afraid. The main, fundamental problem is that the most up-to-date version of `hunspell::hunspell_parse()` does not do what you were hoping it does on all platforms.

``` r
txt <- "C'est l'arriere-cuisine. On s'y trouve."
download.file("https://raw.githubusercontent.com/titoBouzout/Dictionaries/master/French.aff", "French.aff")

hunspell::hunspell_parse(txt, dict = "French.aff")
#> [[1]]
#> [1] "C'est"              "l'arriere-cuisine." "On"                
#> [4] "s'y"                "trouve."
```
It does not split on punctuation; it treats the words basically the same as default tokenization. You can see from the work I've been doing on [Travis](https://travis-ci.org/juliasilge/tidytext/builds) and [Appveyor](https://ci.appveyor.com/project/juliasilge/tidytext/history) that this is true on Linux and Windows, and I also have found this to be true locally on MacOS. I'm not sure why you saw different behavior locally, but this is not going to work here.

The good news here is that it is not hard to do what you want to with normal tidy tools! When I have wanted to treat contractions in English separately, it is just a single line before using `unnest_tokens()` and it gets you exactly what you say you want.

``` r
library(tidyverse)
library(tidytext)
d <- tibble(txt = c("C'est l'arriere-cuisine. On s'y trouve."))

d %>%
  mutate(txt = str_replace_all(txt, "[:punct:]", " ")) %>%
  unnest_tokens(word, txt, token = "ngrams", n = 2)
#> # A tibble: 8 x 1
#>   word           
#>   <chr>          
#> 1 c est          
#> 2 est l          
#> 3 l arriere      
#> 4 arriere cuisine
#> 5 cuisine on     
#> 6 on s           
#> 7 s y            
#> 8 y trouve
```
I am going to remove the code from this PR, the dictionaries, etc. Thank you for your interest in tidytext and for your work on NLP in R!

**Comment by ColinFay** [comment]
Hi @juliasilge 

I think I've found where I made a mistake... I'm honestly sorry about that missed PR :/ 

It seems that the dictionary name must be passed as fr_FR, instead of french.aff

```r
download.file("https://raw.githubusercontent.com/titoBouzout/Dictionaries/master/French.aff", 
              "fr_FR.aff")

dictionary("fr_FR.aff")
# Dic is in the current working directory
<hunspell dictionary>
  affix: /Users/colin/Seafile/ThinkR/documents_colin/R/fr_FR.aff 
dictionary: /Users/colin/Seafile/ThinkR/documents_colin/R/fr_FR.aff 
encoding: ISO8859-1 
wordchars: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþ 
added: 0 custom words

# With the french dictionnary I just downloaded
hunspell::hunspell_parse("C'est l'arriere-cuisine. On s'y trouve.", dict = dictionary("fr_FR.aff"))
[[1]]
[1] "C"       "est"     "l"       "arriere" "cuisine" "On"      "s"       "y"       "trouve" 

# With standard dictionary
hunspell::hunspell_parse("C'est l'arriere-cuisine. On s'y trouve.")
[[1]]
[1] "C'est"     "l'arriere" "cuisine"   "On"        "s'y"       "trouve"   
```
capture d ecran 2017-12-28 a 21 21 55


The thing is, when I try to use the one from a new "updated" {tidytext} : 

```r
dictionary(system.file("fr_FR.aff", package = "tidytext"))
<hunspell dictionary>
  affix: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/tidytext/fr_FR.aff 
dictionary: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/tidytext/fr_FR.aff 
encoding: UTF-8 
wordchars: '-.0123456789’ 
added: 0 custom words
```
It seems that the output is not the same as the one I just got, as we can see from the `wordchars` elements. Which is weird, as it is the very same file. Same happens if I force the download inside the package: 

```r
download.file("https://raw.githubusercontent.com/titoBouzout/Dictionaries/master/French.aff", 
              system.file("fr_FR.aff", package = "tidytext"))
dictionary(system.file("fr_FR.aff", package = "tidytext"))
<hunspell dictionary>
 affix: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/tidytext/fr_FR.aff 
 dictionary: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/tidytext/fr_FR.aff 
 encoding: UTF-8 
 wordchars: '-.0123456789’ 
 added: 0 custom words
```
If it's ok with you, I'll investigate into this and make you a new PR?

**Comment by juliasilge** [comment]
I lean toward not pursuing this dictionary-based method for splitting text. There are a couple main reasons, aside from the challenge of it not working quite right at the moment.

- Conceptually, depending on dictionaries is quite different than the process of tokenization.
- I don't yet see anything a user might need to do that isn't already possible, quite easily. Is there something you want to be able to do that you can't do with, for example, handling punctuation before tokenizing the way I have above? This is just an addition of one line, and very much in the spirit of flexible, powerful tidy tools for text, etc. Is there a reason this approach does not meet analysis needs?
- We cannot depend on unexported functions from another package, the way there was use of `getFromNamespace` in this PR; that's a no go for dependency stability. This would mean that this dictionary-based splitting of text could only be for single words like the other hunspell-dependent options, not ngrams, etc. This is pretty limited from an analysis standpoint, especially when there is a different option for this use case (handle punctuation before tokenization).

**Comment by ColinFay** [comment]
The processing before tokenization is fine to me. My will to integrate this in `unnest_tokens` was that if every time I want to tokenize french I have to do the same pre-processing, I tend to prefer a solution where I don't need to rewrite / copy and paste the same line of code each time. Plus, this is a very "local" (in the sense that I have it in my workflow), hence not directly sharable for everyone using the package. 

A dictionnary based would have been better for french as regex tokenization does not work as we would expect at the end of the day. For example, `aujourd'hui` is one word in french, and splitting by `'` does not work here. And it can be an important token in some time based analysis, as it means today. I guess in that case we can go for searching "aujourd', though. But french is not that easy a language to tokenize with a simple regex : same goes for words like `entr'apercevoir`, `prud'homme` and other french peculiar words with an apostrophe in the middle. 

Another example that I did lately is analysing the pronouns in a text, and `s'il te plaît` (please) is not well split on spaces, as it can't be counted as an occurence of `il` (he) `te` (you) `plait` (it pleases). And we have a lot of weird cases like these in french :) I don't know well other languages to tell, but I guess we can find the same in other non-english languages. 

But I  understand that this dictionnary based solution does not match with what we would expect in {tidytext}. Really sorry if I have wasted your time with this PR and comments, I just love what you did with this package, and I would like to help as much as I can to make it usable with other languages.

**Comment by juliasilge** [comment]
Hmmmm, OK, those are some good thoughts to consider that are specific to French. Let's see how things move forward with tokenizers and whether there are eventually exported functions that we can eventually use to find ngrams and such.

**Comment by ColinFay** [comment]
Maybe the safest way would be to implement the possibility to provide a custom hunspell dictionary to the function, with a vignette explaining where to find these dict, how to implement, and how to use a custom dict. That way, it wouldn't rely on the dictionaries contained in the package. 

The biggest issue for now is indeed that it would rely on unexported {tokenizers} functions to do ngrams and skip ngrams. One solution would be to implement our own functions to do that. I'll dig into that, and I'll keep you informed as soon as I have something interesting :)

**Pull request merged**
