### PR TITLE
data_frame() soft-deprecated from tibble v2.00 & devtools::revdep_check() deprecated 

### PR DESCRIPTION
**Pull request by luisdza**
Down the rabbit hole  ... I started with tidy-text-mining book and I ended up here. :construction_worker:

**Breaking changes** from [tibble v2.00](https://github.com/tidyverse/tibble/releases/tag/v2.0.0)
* as.tibble() and as_data_frame() are officially deprecated and not generic anymore, please use/implement as_tibble() (#111).
* data_frame() and frame_data() are soft-deprecated, please use tibble() or tribble() (#111).

### CODE REVIEW

**Comment by luisdza** [comment]
AppVeyor failure seems to be caused by compilation of the XML package.

"There are binary versions available but the source versions are later:
             binary    source needs_compilation
XML       3.98-1.16 3.98-1.17              TRUE"

"DocParse.h:18:27: fatal error: libxml/parser.h: No such file or directory"

Looks like other people are having the same issue: https://github.com/krlmlr/r-appveyor/issues/138

**Comment by luisdza** [comment]
I included this to force the rebuild:
devtools::revdep_check() deprecated in favour of revdepcheck package
https://github.com/r-lib/devtools/issues/1553

**Comment by luisdza** [comment]
Binary version of latest XML package is now available.
https://cran.rstudio.com/bin/windows/contrib/3.5/XML_3.98-1.17.zip

AppVeyor build is happy.

**Comment by juliasilge** [comment]
Thank you so much! 🎉

**Pull request merged**
