### PR TITLE
Use the travis apt addon

### PR DESCRIPTION
**Pull request by jimhester**

### CODE REVIEW

**Comment by juliasilge** [comment]
@dgrtwo The original PR passed on Travis (https://travis-ci.org/juliasilge/tidytext/builds/131783358), but when you merged it, it looks like one of the tests failed. I saw this particular test fail once before. Do you know what is going on?

**Comment by dgrtwo** [comment]
Yes- I just realized I had assumed an LDA output wouldn't be stochastic when it was at least a little stochastic. Whoops! Just removed that test (it would be a quite obscure way for it to fail) and it shouldn't happen again.

**Comment by juliasilge** [comment]
@dgrtwo I am writing a blog post on using Travis for beginners that @jimhester gave me feedback on (hence the PR on our .travis.yml) so it would be really good if all my packages were passing on Travis whenever I publish it. 😬 Thanks for taking care of that test!

**Comment by dgrtwo** [comment]
I'll be more careful! No more `expect_equal(sample(2, 1), 1)` for me

**Pull request merged**
