### PR TITLE
Fix #50

### LINKED ISSUE #50: tidytext::get_sentiments() fails if tidytext not loaded
To reproduce,

1. Don't call `library(tidytext)`.
2. Call `tidytext::get_sentiments()`.

The problem is that `sentiments` doesn't get loaded if tidytext isn't on the search path.

I think the fix is to add

```r
data(list = "sentiments", package = "tidytext")
```

somewhere near the start of `get_sentiments()`.

You might also need to specify the `enivr` argument to `data()`.

### PR DESCRIPTION
**Pull request by Ironholds**
What it says on the tin!

### CODE REVIEW

**Comment by juliasilge** [comment]
@Ironholds can you add yourself as a contributor in DESCRIPTION?

**Comment by Ironholds** [comment]
And done! (I've now got the fix for the data.table issue done, by the way - writing an explanatory note in the bug proper just so yinz can see the rationale behind my work, and then a unit test)

**Comment by Ironholds** [comment]
Oh balls

**Comment by juliasilge** [comment]
Closes #50

**Pull request merged**
