### PR TITLE
Fix tests and #34

### PR DESCRIPTION
**Pull request by Ironholds**
This patch fixes a pair of bugs in the unit tests, respectively:

1. Where the topicmodels package was required, but part of both a quiet require() test *and* a library call...meaning that if the package wasn't loaded, it'd die on library() and the nice require check would be for naught.

2. Where the quanteda package and its underlying `dfmSparse` class were assumed loaded, which wasn't a guarantee or check that the test file performed.

In addition, it turns unnest_tokens into an S3 generic, as requested by #34 - I figure I'll build a data.table method in as the next patch.

### CODE REVIEW

**Comment by Ironholds** [comment]
Hmn. Curious; it doesn't like tibbles, even though `unnest_tokens` now has a default. @dgrtwo ideas?

**Comment by Ironholds** [comment]
Okay, this should now be fixed! Also cleaned the documentation a bit - looks like there were a couple of stray definitions around.

**Comment by Ironholds** [comment]
Next up after this I'm gonna fix #37 , #38 and #50 if that works for y'all

**Comment by juliasilge** [comment]
We definitely want to address #37 and #50 before the next CRAN release, Oliver. :raised_hands::raised_hands::raised_hands:

**Comment by Ironholds** [comment]
Grand! Is the next version intended to be 0.2.0 or 0.1.4? (trying to make sure that I don't break semantic versioning in the issues I intend to pick up)

**Comment by juliasilge** [comment]
The next CRAN version will actually be 0.1.3 (that is the current development version). On [CRAN right now we have 0.1.2](https://cran.r-project.org/package=tidytext).

**Comment by Ironholds** [comment]
Aha! Okay, I'll tweak the NEWS in my next patch.

**Pull request merged**
