### PR TITLE
Feature/Tidiers for STM estimateEffect

### PR DESCRIPTION
**Pull request by jefferickson**
Hello @juliasilge ,

I needed this implemented for a project I'm working on, so I thought I'd send it over in a PR in case you want to merge it in.

One question I have is I don't fully understand the separation between model tidiers included in `tidytext` versus including them in `broom`. Is there an intended separation between the two? I'd also be happy to adapt this to the `broom` package if you think that would be more appropriate.

Let me know if you want to discuss. Thank you!

Cheers,
Jeff

### CODE REVIEW

**Comment by jefferickson** [comment]
@dgrtwo I'll ping you too because of your involvement in both packages also. See my comment above. Any opinion about which package this should live in and where the line between the two stands?

Cheers,
Jeff

**Comment by juliasilge** [comment]
Thank you so much for working on this! And yes, this belongs here in tidytext, not in broom. I will review this thoroughly ASAP and get it merged in.

**Comment by jefferickson** [comment]
Hi @juliasilge , let me know if there is anything I can do to help get this merged.

Thanks!
Jeff

**Comment by juliasilge** [comment]
Thank you so much @jefferickson! 🙌

**Pull request merged**
