### PR TITLE
Simplify get_sentiments()

### PR DESCRIPTION
**Pull request by jennybc**
I was following a thread that started with R Packages revisions, then went to `available::available()`, which had me poking here. This seemed like a great candidate for a little `switch()` action 🙂

The error messages lost a bit of specific verbiage/capitalization, which I could restore if that seems worth it.

### CODE REVIEW

**Comment by juliasilge** [comment]
Thanks so much for this improvement! 🙌

**Comment by hadley** [comment]
Would you mind if I used this as small case study in https://principles.tidyverse.org?

**Comment by juliasilge** [comment]
@hadley Sure thing! I'm really glad to have all these repetitions of `if` cleaned up.

**Comment by hadley** [comment]
Thanks @juliasilge!

**Pull request merged**
