### PR TITLE
Added character_shingles as token for char ngrams

### LINKED ISSUE #103: Adding functionality for character ngrams in unnest_tokens
Hello!

I was wondering if the ```n``` parameter could be enabled in the ```unnest tokens``` function for ```token = "characters"``` so that we can get more than just single characters for character ngrams. I've been using them as features in my nlp-based research and they seem to capture a lot of information while also reducing the total number of features in the matrix that goes into the model. 

I also really want to implement this and I'm going to try some trial and error in the ```unnest_tokens.R``` code in my forked repo(but I have limited understanding of it so I have to spend some significant time reading).

### PR DESCRIPTION
**Pull request by kanishkamisra**
Now that I think about it, I should probably put it as character_ngrams for the ```tokens``` parameter and put an if statement to adjust the call to ```tokenize_character_shingles()``` from the ```tokenizers``` package. Please let me know your thoughts on this and I will make the necessary changes!

This fixes #103 

Happy to contribute :)

### CODE REVIEW

**Comment by juliasilge** [comment]
This is great! Thank you so much for interest in this package. I think we should keep the name consistent with what tokenizers uses.

One thing we do need is a test. Would you like to write it? Or I can do it. I would like to see it like the [test for unnesting by character](https://github.com/juliasilge/tidytext/blob/85da3e67e834d1652a31ff5e4e27184d27e6ab4b/tests/testthat/test-unnest-tokens.R#L7), in the same file.

**Comment by kanishkamisra** [comment]
I can try it! Thanks for the opportunity! 😄

**Comment by juliasilge** [comment]
Thank you so much! 👏 Now, one more thing... Can you add yourself to [DESCRIPTION](https://github.com/juliasilge/tidytext/blob/master/DESCRIPTION) as a contributor? We are listed alphabetically by last name.

**Comment by kanishkamisra** [comment]
Thanks Julia! :D

**Pull request merged**
